// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecApp(arg1) {
  return window['go']['main']['App']['ExecApp'](arg1);
}

export function GetApps(arg1) {
  return window['go']['main']['App']['GetApps'](arg1);
}

export function HideApp() {
  return window['go']['main']['App']['HideApp']();
}

export function ShowApp() {
  return window['go']['main']['App']['ShowApp']();
}
