// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecApp(arg1:main.DesktopApp):Promise<void>;

export function GetApps(arg1:string):Promise<Array<main.DesktopApp>>;

export function Greet(arg1:string):Promise<string>;
