// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecApp(arg1) {
  return window['go']['app']['App']['ExecApp'](arg1);
}

export function GetApps(arg1) {
  return window['go']['app']['App']['GetApps'](arg1);
}

export function GetGlobalInputValue() {
  return window['go']['app']['App']['GetGlobalInputValue']();
}

export function GetPlugins() {
  return window['go']['app']['App']['GetPlugins']();
}

export function GetSelectionIdx() {
  return window['go']['app']['App']['GetSelectionIdx']();
}

export function HideApp() {
  return window['go']['app']['App']['HideApp']();
}

export function SetGlobalInputValue(arg1) {
  return window['go']['app']['App']['SetGlobalInputValue'](arg1);
}

export function SetSelectionIdx(arg1) {
  return window['go']['app']['App']['SetSelectionIdx'](arg1);
}

export function ShowApp() {
  return window['go']['app']['App']['ShowApp']();
}
