// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ExecApp(arg1:app.DesktopApp):Promise<void>;

export function GetApps(arg1:string):Promise<Array<app.DesktopApp>>;

export function HideApp():Promise<void>;

export function ShowApp():Promise<void>;
