// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ExecApp(arg1:app.DesktopApp):Promise<void>;

export function GetApps(arg1:string):Promise<Array<app.DesktopApp>>;

export function GetCachedDesktopApps():Promise<Array<app.DesktopApp>>;

export function GetGlobalInputValue():Promise<string>;

export function GetPlugins():Promise<Array<app.Plugin>>;

export function GetSelectionIdx():Promise<number>;

export function HideApp():Promise<void>;

export function SetGlobalInputValue(arg1:string):Promise<void>;

export function SetSelectionIdx(arg1:number):Promise<void>;

export function ShowApp():Promise<void>;
